Add reproducers for concurrency test failure
Two out of the three `testConcurrencyAccess` tests crash when run.
The key is that if these tests have unrestricted availability, then
the `for await _ in group {}` causes a crash, i.e.:

error: Exited with unexpected signal code 11

The `testConcurrencyAccess1` does not have unrestricted availability,
so it runs without failure.